In [1]:
import numpy as np
import pandas as pd
from src.latin_square import LatinSquare

from ngboost import NGBRegressor

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

def get_cost(x):
    _, counts = np.unique(x, return_counts=True)
    return np.sum(counts-1)

In [2]:
data = LatinSquare()

In [3]:
data.y

array([0.55158069, 0.65231258, 0.57633761, 0.55483215, 0.62616363,
       0.57856432, 0.55021382, 0.70058265, 0.60785565, 0.5795674 ,
       0.6524937 , 0.49936448, 0.57576296, 0.55500049, 0.60217323,
       0.58068584, 0.47568209, 0.60244151, 0.58610834, 0.6053634 ,
       0.5769773 , 0.65441721, 0.65416622, 0.56023097, 0.52844744,
       0.68497204, 0.62742284, 0.52696375, 0.65304145, 0.55449567,
       0.6261438 , 0.50556532, 0.55217003, 0.57841811, 0.55006951,
       0.64897806, 0.65190225, 0.60517595, 0.65314514, 0.57791182,
       0.58196642, 0.50219449, 0.57846481, 0.58047412, 0.65446757,
       0.7314072 , 0.70121782, 0.60132676, 0.52904435, 0.60312942,
       0.60560532, 0.6806323 , 0.60017217, 0.55387384, 0.50066067,
       0.7744109 , 0.65160803, 0.60236705, 0.57431526, 0.62963641,
       0.60459206, 0.60016802, 0.57935502, 0.55699379, 0.6755264 ,
       0.58017849, 0.6261522 , 0.58129406, 0.57665686, 0.6276678 ,
       0.60851562, 0.60361411, 0.62807726, 0.57772377, 0.52664

In [11]:
ngb = NGBRegressor().fit(data.X, data.y)
Y_preds = ngb.predict(data.X)
Y_dists = ngb.pred_dist(data.X)

[iter 0] loss=-1.4617 val_loss=0.0000 scale=1.0000 norm=0.5360
[iter 100] loss=-1.8328 val_loss=0.0000 scale=1.0000 norm=0.3446
[iter 200] loss=-2.0972 val_loss=0.0000 scale=1.0000 norm=0.3172
[iter 300] loss=-2.3696 val_loss=0.0000 scale=1.0000 norm=0.3032
[iter 400] loss=-2.6391 val_loss=0.0000 scale=1.0000 norm=0.2933


In [4]:
cand = data.generate_candidate()
cand

array([[2., 1., 2., 4., 0., 3., 1., 3., 2., 4., 0., 1., 3., 0., 3., 2.,
        1., 0., 4., 4., 2., 4., 4., 4., 2.]])

In [7]:
cands = data.generate_candidates_idx(cand, 0)

In [9]:
cands_p = data.dummify( cands )

In [14]:
preds = ngb.pred_dist(cands_p) 

In [16]:
a = preds[0]

In [21]:
a.loc

0.5744025463686706

In [25]:
a.dist.logpdf(0.58)

2.891465648774309

In [5]:
np.arange(5).astype(float)

array([0., 1., 2., 3., 4.])

In [7]:
data.y.max()

0.7296409412924634

In [6]:
c = np.ones([1,25])
data.compute_obj(data.dummify(c) )

0.006887078819275064

In [1]:
rows = np.apply_along_axis(get_cost, axis=0, arr=c.reshape(5,5))
cols = np.apply_along_axis(get_cost, axis=1, arr=c.reshape(5,5))

NameError: name 'np' is not defined

In [25]:
np.sum(rows+cols)

40

In [10]:
init_pred = ngb.pred_dist(data.dummify(c))

In [12]:
init_pred.sample(100)

array([18.66476613, 16.8692063 , 15.03678282, 17.61453354, 17.90825017,
       17.0570301 , 16.73400635, 16.98311045, 14.87826865, 16.63414253,
       18.87481653, 17.2118898 , 17.48403266, 17.12459367, 15.47154466,
       16.68592651, 15.89629989, 16.1711064 , 15.76671527, 15.27805481,
       17.32286997, 17.69221325, 16.47865965, 19.91290278, 16.83895255,
       17.52782599, 15.48245609, 17.65565849, 18.74773747, 19.07701282,
       15.36883774, 17.86093841, 15.99115732, 14.87432109, 16.26404577,
       16.59911649, 16.19359452, 16.37985194, 16.97693123, 17.58872714,
       16.38753629, 17.39341724, 17.11829535, 16.63588253, 15.14797235,
       16.6075937 , 16.54349894, 17.06252946, 17.36573233, 19.01139697,
       19.50447719, 16.34671367, 16.93053091, 16.65490384, 16.80868096,
       16.00240061, 17.82682853, 15.76346621, 17.92598655, 15.86495944,
       15.631008  , 16.21725503, 16.11512544, 16.49820096, 16.59503565,
       16.28133074, 15.8648301 , 17.50784985, 16.4061561 , 17.05

In [5]:
data.dummify(data.generate_candidate(1), l=5)

array([[0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
        0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.]])

In [13]:
ngb.pred_dist(data.dummify(data.generate_candidate(1), l=5).reshape(1,-1))

In [12]:
mean_squared_error(data.y, Y_preds)

0.5126569590722849

In [13]:
Y_dists[0].dist.logpdf(14.)

-6.453736088453643